[package]
name = "rust-whisperx-bench"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
anyhow = "1"
audio-analysis-transcription = { package = "moenarch-audio-analysis-transcription", version = "=0.1.15", default-features = false, features = ["cuda"] }
hound = "3.5"
serde_json = "1"
sha2 = "0.10"
